#!/bin/bash
#SBATCH -A test                             # 自己所属的账户 (不要改)
#SBATCH -J DSS_GraNet  # 所运行的任务名称 (自己取)
#SBATCH -N 1                                # 占用的节点数（根据代码要求确定）
#SBATCH --ntasks-per-node=1                 # 运行的进程数（根据代码要求确定）
#SBATCH --cpus-per-task=1                  # 每个进程的CPU核数 （根据代码要求确定）
#SBATCH --gres=gpu:1                        # 占用的GPU卡数 （根据代码要求确定）
#SBATCH -p all                           # 任务运行所在的分区 (根据代码要求确定，gpu为gpu分区，gpu4为4卡gpu分区，cpu为cpu分区)
#SBATCH -t 1-00:00:00                     # 运行的最长时间 day-hour:minute:second，但是请按需设置，不要浪费过多时间，否则影响系统效率
#SBATCH -o test.out     # 打印输出的文件

source /home/TUE/20180170/miniconda3/etc/profile.d/conda.sh
source activate torch151

data=cifar10
model=wrn-28-10
epoch=250
for seed in 18 19 20
do
  python main_DST.py --sparse --model $model --data $data --seed $seed  --sparse-init ERK --update-frequency 1000 --batch-size 128 --death-rate 0.5 --large-death-rate 0.8 --growth gradient --death magnitude --redistribution none --epochs $epoch --density 0.2
done

data=cifar100
model=wrn-28-10
epoch=250
for seed in 18 19 20
do
  python main_DST.py --sparse --model $model --data $data --seed $seed  --sparse-init ERK --update-frequency 1000 --batch-size 128 --death-rate 0.5 --large-death-rate 0.8 --growth random --death magnitude --redistribution none --epochs $epoch --density 0.2
one


conda activate torch151