#!/bin/bash
#SBATCH --job-name=freeticket_PF
#SBATCH -p gpu
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=1
#SBATCH --gpus=1
#SBATCH -t 0-5:59:59
#SBATCH --cpus-per-task=18
#SBATCH -o freeticket_PF.out

source /home/sliu/miniconda3/etc/profile.d/conda.sh
source activate LoRA

python3 main_individual.py  --model wrn-28-10 --data cifar10 --decay-schedule cosine --seed 18 \
--sparse-init ERK --update-frequency 1000 --batch-size 128 --death-rate 0.5 --large-death-rate 0.5 \
--growth gradient --death magnitude --redistribution none --epochs 250 --density 0.2

source deactivate
